Add a custom runner

diff --git a/.github/workflows/conda-build-test.yml b/.github/workflows/conda-build-test.yml
--- a/.github/workflows/conda-build-test.yml
+++ b/.github/workflows/conda-build-test.yml
@@ -1,114 +1,137 @@
-name: Conda build and test
+name: Build and test
+run-name: ${{ inputs.run_name }}
 
 on:
   workflow_dispatch:
-  schedule:
-    - cron: "5 2 * * *"
-  #FIXME
+    inputs:
+      runner_label:
+        description: Runner label, keep empty for default
+        type: string
+        default: ""
+      pytorch_ref:
+        description: PyTorch ref, keep empty for default
+        type: string
+        default: ""
+      pytorch_mode:
+        description: PyTorch mode, source or wheels
+        type: choice
+        options:
+          - source
+          - wheels
+        default: source
+      upload_test_reports:
+        description: Upload test reports
+        type: boolean
+        default: false
+      ignore_errors:
+        description: Ignore test errors
+        type: boolean
+        default: false
+      skip_list:
+        description: Skip list
+        type: string
+        default: ""
+      run_name:
+        description: Custom run name
+        type: string
+        default: "Build and test"
+      enable_unskip:
+        description: Ignore pytest.skip
+        type: boolean
+        default: false
+
+  pull_request:
+    branches:
+      - main
   push:
+    branches:
+      - main
 
 permissions: read-all
 
-env:
-  BACKEND: XPU
-  TRITON_DISABLE_LINE_INFO: 1
-  GH_TOKEN: ${{ github.token }}
-
 jobs:
-
-  integration-tests:
-    name: Integration tests
-    runs-on:
-      - max1100
-      - rolling
-      - runner-0.0.19
-    strategy:
-      matrix:
-        python: ${{ github.ref_name == 'main' && fromJson('["3.9", "3.10", "3.11"]') || fromJson('["3.9"]') }}
-    defaults:
-      run:
-        shell: bash -noprofile --norc -eo pipefail -c "source /opt/intel/oneapi/setvars.sh > /dev/null; source {0}"
+  pre-commit:
+    name: Pre-commit checks
+    runs-on: Linux
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Calculate env
-        run: |
-          echo $HOME/miniforge3/bin >>$GITHUB_PATH
-
-      - name: Load conda cache
-        id: conda-cache
+      - name: Load pip cache
+        id: pip-cache
         uses: ./.github/actions/load
         env:
-          CACHE_NUMBER: 5
+          # Increase this value to reset cache
+          CACHE_NUMBER: 2
         with:
-          path: $HOME/miniforge3/envs/triton
-          key: conda-py${{ matrix.python }}-${{ hashFiles('scripts/triton.yml', 'python/pyproject.toml', 'python/setup.py', '.github/pins/ipex.txt', '.github/pins/pytorch.txt') }}-${{ env.CACHE_NUMBER }}
+          path: $HOME/.cache/pip
+          key: pip-3.10-${{ hashFiles('.pre-commit-config.yaml') }}-${{ env.CACHE_NUMBER }}
 
-      - name: Update conda env
-        if: ${{ steps.conda-cache.outputs.status == 'miss' }}
-        run: |
-          conda create -n triton --override-channels -c conda-forge python=${{ matrix.python }}.*
-          conda env update -f scripts/triton.yml
-          find /opt/intel/oneapi/ \( -name '*.so' -or -name '*.so.*' \) -exec cp -n {} $HOME/miniforge3/envs/triton/lib \;
-          ln -snf /usr/include/level_zero $HOME/miniforge3/envs/triton/bin/../x86_64-conda-linux-gnu/sysroot/usr/include/level_zero
-          find /usr -name libze_\* -exec cp -n {} $HOME/miniforge3/envs/triton/lib \;
-
-      - name: Add conda info to log
-        run: |
-          conda info
-          conda list -n triton
-
-      - name: Install latest nightly wheels
-        uses: ./.github/actions/install-wheels
+      - name: Install Python 3.10
+        uses: actions/setup-python@v5
         with:
-          gh_token: ${{ secrets.GITHUB_TOKEN }}
-          install_cmd: conda run --no-capture-output -n triton pip install
-          python_version: ${{ matrix.python }}
-          wheels_pattern: 'torch-*'
+          python-version: '3.10'
 
-      - name: Build Triton
+      - name: Run pre-commit checks
         run: |
           set -x
-          export DEBUG=1
-          cd python
-          conda run --no-capture-output -n triton pip install pybind11
-          conda run --no-capture-output -n triton pip install --no-build-isolation -e '.[build,tests,tutorials]'
+          pip install --upgrade pre-commit
 
-      - name: Run core tests
-        env:
-          # FIXME https://github.com/intel/intel-xpu-backend-for-triton/issues/806
-          # FIXME https://github.com/intel/intel-xpu-backend-for-triton/issues/841
-          TRITON_TEST_SKIPLIST_DIR: scripts/skiplist/conda
-        run: |
-          set -x
-          conda run --no-capture-output -n triton bash -v -x scripts/test-triton.sh
+          # TODO: ignore the first yapf failure until https://github.com/google/yapf/issues/1164 is fixed
+          python3 -m pre_commit run --all-files --verbose yapf &> /dev/null || true
+          # If first run of yapf worked and made changes reset the tree to the original state
+          git reset --hard
 
-      - name: Run E2E test
-        run: |
-          cd ../pytorch || {
-            PYTORCH_COMMIT_ID=$(<.github/pins/pytorch.txt)
-            cd ..
-            git clone --single-branch -b dev/triton-test-3.0 --recurse-submodules https://github.com/Stonepia/pytorch.git
-            cd pytorch
-            git branch pin-branch $PYTORCH_COMMIT_ID
-            git switch pin-branch
-          }
+          python3 -m pre_commit run --show-diff-on-failure --color=always --all-files --verbose
 
-          TRANSFORMERS_VERSION="$(<.ci/docker/ci_commit_pins/huggingface.txt)"
-          conda run -n triton pip install pyyaml pandas scipy numpy psutil pyre_extensions torchrec transformers==$TRANSFORMERS_VERSION
-
-          # Set WORKSPACE for inductor_xpu_test.sh to make sure it creates "inductor_log" outside of pytorch cloned directory
-          export WORKSPACE=$GITHUB_WORKSPACE
-          # TODO: Find the fastest Hugging Face model
-          conda run --no-capture-output -n triton $GITHUB_WORKSPACE/scripts/inductor_xpu_test.sh huggingface float32 inference accuracy xpu 0 static 1 0 AlbertForMaskedLM
-          # The script above always returns 0, so we need an additional check to see if the accuracy test passed
-          cat $WORKSPACE/inductor_log/*/*/*.csv
-          grep AlbertForMaskedLM $WORKSPACE/inductor_log/*/*/*.csv | grep -q ,pass,
-
-      - name: Save conda cache
-        if: ${{ steps.conda-cache.outputs.status == 'miss' }}
+      - name: Save pip cache
+        if: ${{ steps.pip-cache.outputs.status == 'miss' }}
         uses: ./.github/actions/save
         with:
-          path: ${{ steps.conda-cache.outputs.path }}
-          dest: ${{ steps.conda-cache.outputs.dest }}
+          path: ${{ steps.pip-cache.outputs.path }}
+          dest: ${{ steps.pip-cache.outputs.dest }}
+
+  prepare:
+    name: Prepare
+    runs-on: Linux
+
+    outputs:
+      matrix: ${{ steps.matrix.outputs.matrix }}
+
+    steps:
+      - name: Inputs
+        run: |
+          cat <<EOF
+          ${{ toJSON(inputs) }}
+          EOF
+
+      - name: Matrix
+        id: matrix
+        run: |
+          if [[ -n "${{ inputs.runner_label }}" ]]; then
+            matrix='{"python": ["3.9"]}'
+          else
+            matrix='{"python": ["3.9"], "driver": ["rolling", "lts"]}'
+          fi
+          echo "matrix=$matrix" | tee -a $GITHUB_OUTPUT
+
+  integration-tests:
+    name: Integration tests matrix
+    needs: prepare
+
+    strategy:
+      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
+
+    uses: ./.github/workflows/build-test-reusable.yml
+    with:
+      driver_version: ${{ matrix.driver }}
+      runner_label: ${{ inputs.runner_label }}
+      pytorch_ref: ${{ inputs.pytorch_ref }}
+      pytorch_mode: ${{ inputs.pytorch_mode || 'source' }}
+      python_version: ${{ matrix.python }}
+      upload_test_reports: ${{ inputs.upload_test_reports || false }}
+      ignore_errors: ${{ inputs.ignore_errors || false }}
+      skip_list: ${{ inputs.skip_list }}
+      run_name: ${{ inputs.run_name }}
+      enable_unskip: ${{ inputs.enable_unskip || false }}
+      env_manager: conda
