Add pre-commit for the repo (#30)
* Add pre-commit

* [Format] Format code to following pre-commit settings

diff --git a/.github/workflows/triton_xpu_backend_ci.yml b/.github/workflows/triton_xpu_backend_ci.yml
--- a/.github/workflows/triton_xpu_backend_ci.yml
+++ b/.github/workflows/triton_xpu_backend_ci.yml
@@ -9,7 +9,7 @@ on:
 jobs:
 
   Integration-Tests:
- 
+
     runs-on: [self-hosted, PVC]
 
     steps:
@@ -19,32 +19,13 @@ jobs:
           source ${HOME}/env_triton.sh
           source ${HOME}/miniconda3/bin/activate triton-preci
           conda install -y astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses mkl mkl-include
-      
-      - name: Install Dependency
-        shell: bash
-        run: |
-          set -ex
-          python --version
-          source ${HOME}/miniconda3/bin/activate triton-preci
-          python --version
-          pip install setuptools cython numpy wheel scikit-build scipy
-          ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ${HOME}/miniconda3/envs/triton-preci/lib/libstdc++.so.6
-          pip install psutil cpuid
-          bash ${HOME}/triton-preci/env_prepare_ci.sh
-          python -c "import torch;import intel_extension_for_pytorch"
-          if [ ${PIPESTATUS[0]} -ne 0 ]; then
-              echo -e "[ERROR] Private-torch or IPEX BUILD FAIL"
-              exit 1
-          fi
+          conda install -y -c conda-forge libstdcxx-ng
+          python3 -m pip install --upgrade pre-commit
 
-      - name: Build Triton
+      - name: Check Pre-commit
         shell: bash
         run: |
-          set -ex
           source ${HOME}/miniconda3/bin/activate triton-preci
-          source ${HOME}/env_triton.sh
-          pip uninstall -y triton
-          export LLVM_SYSPATH=${HOME}/triton-preci/llvm/build/
           rm -rf triton
           git clone https://github.com/openai/triton triton
           cd triton
@@ -55,25 +36,49 @@ jobs:
           cd third_party/intel_xpu_backend
           git checkout ${{github.event.pull_request.head.ref}} && git pull
           git branch
-          cd ../../python
+          python3 -m pre_commit run --all-files
+
+      - name: Install Dependency
+        shell: bash
+        run: |
+          python --version
+          source ${HOME}/miniconda3/bin/activate triton-preci
+          python --version
+          pip install setuptools cython numpy wheel scikit-build scipy
+          pip install psutil cpuid
+          bash ${HOME}/triton-preci/env_prepare_ci.sh
+          python -c "import torch;import intel_extension_for_pytorch"
+          if [ ${PIPESTATUS[0]} -ne 0 ]; then
+              echo -e "[ERROR] Private-torch or IPEX BUILD FAIL"
+              exit 1
+          fi
+
+      - name: Build Triton
+        shell: bash
+        run:  |
+          source ${HOME}/miniconda3/bin/activate triton-preci
+          source ${HOME}/env_triton.sh
+          export LLVM_SYSPATH=${HOME}/triton-preci/llvm/build/
+          pip uninstall -y triton
+          cd triton/python
           python setup.py clean
           TRITON_CODEGEN_INTEL_XPU_BACKEND=1 python setup.py develop
+          python -c "import triton"
           if [ ${PIPESTATUS[0]} -ne 0 ]; then
-              echo -e "[ERROR] Private-torch BUILD FAIL"
+              echo -e "[ERROR] Triton BUILD FAIL"
               exit 1
           fi
 
       - name: Unit Test for triton on PVC
         shell: bash
         run: |
-          set -ex
           echo -e "[ INFO ] Run UT test on Node $(hostname)"
           source ${HOME}/miniconda3/bin/activate triton-preci
           source ${HOME}/env_triton.sh
           export LLVM_SYSPATH=${HOME}/triton-preci/llvm/build/
           pip install pytest
           rm -rf ~/.triton/cache
-          export TRITON_LIBDEVICE_PATH=${HOME}/actions-runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/triton/python/triton/third_party/xpu/ 
+          export TRITON_LIBDEVICE_PATH=${HOME}/actions-runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/triton/python/triton/third_party/xpu/
           rm -rf triton-tests
           bash ${HOME}/triton-preci/case_prepare_ci.sh
           cd ${HOME}/actions-runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/triton-tests/python/test/unit
@@ -111,7 +116,7 @@ jobs:
           echo "num_skipped: $num_skipped" | tee -a ./ut_summary.log
           echo "num_failed: $num_failed" | tee -a ./ut_summary.log
           echo "num_passed: $num_passed" | tee -a ./ut_summary.log
-      
+
       - name: New Failed Cases
         run: |
           echo "TODO: will add new failure cases"
@@ -137,7 +142,7 @@ jobs:
           echo "num_expected_skip_and_sucess: $num_expected_skip_and_sucess" | tee -a ./ut_summary.log
           echo "num_total_wo_mat_dot: $num_total_wo_mat_dot" | tee -a ./ut_summary.log
           echo "total_pass_rate: $total_pass_rate" | tee -a ./ut_summary.log
-      
+
       - name: Float32 Cases Pass Rate Calculate (no matmul/dot)
         run: |
           cd ${HOME}/actions-runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/triton-tests/python/test/unit
diff --git a/.github/workflows/triton_xpu_backend_nightly.yml b/.github/workflows/triton_xpu_backend_nightly.yml
--- a/.github/workflows/triton_xpu_backend_nightly.yml
+++ b/.github/workflows/triton_xpu_backend_nightly.yml
@@ -18,29 +18,12 @@ jobs:
           source ${HOME}/env_triton.sh
           source ${HOME}/miniconda3/bin/activate triton-nightly-test
           conda install -y astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses mkl mkl-include
-      
-      - name: Install Dependency
-        run: |
-          python --version
-          source ${HOME}/miniconda3/bin/activate triton-nightly-test
-          python --version
-          pip install setuptools cython numpy wheel scikit-build scipy
-          ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ${HOME}/miniconda3/envs/triton-nightly-test/lib/libstdc++.so.6
-          pip install psutil cpuid
-          cd ${HOME}/triton-nightly
-          bash ${HOME}/triton-nightly/env_prepare_nightly.sh
-          python -c "import torch;import intel_extension_for_pytorch"
-          if [ ${PIPESTATUS[0]} -ne 0 ]; then
-              echo -e "[ERROR] Private-torch or IPEX BUILD FAIL"
-              exit 1
-          fi
-          
-      - name: Build Triton
+          conda install -y -c conda-forge libstdcxx-ng
+          python3 -m pip install --upgrade pre-commit
+
+      - name: Check Pre-commit
         run: |
           source ${HOME}/miniconda3/bin/activate triton-nightly-test
-          source ${HOME}/env_triton.sh
-          pip uninstall -y triton
-          export LLVM_SYSPATH=${HOME}/triton-nightly/llvm/build/
           rm -rf triton
           git clone https://github.com/openai/triton triton
           cd triton
@@ -50,11 +33,36 @@ jobs:
           git submodule update --init --recursive --jobs 0
           cd third_party/intel_xpu_backend
           git checkout main && git pull
-          cd ../../python
+          python3 -m pre_commit run --all-files
+
+      - name: Install Dependency
+        run: |
+          python --version
+          source ${HOME}/miniconda3/bin/activate triton-nightly-test
+          python --version
+          pip install setuptools cython numpy wheel scikit-build scipy
+          pip install psutil cpuid
+          cd ${HOME}/triton-nightly
+          bash ${HOME}/triton-nightly/env_prepare_nightly.sh
+          python -c "import torch;import intel_extension_for_pytorch"
+          if [ ${PIPESTATUS[0]} -ne 0 ]; then
+              echo -e "[ERROR] Private-torch or IPEX BUILD FAIL"
+              exit 1
+          fi
+
+      - name: Build Triton
+        shell: bash
+        run:  |
+          source ${HOME}/miniconda3/bin/activate triton-nightly-test
+          source ${HOME}/env_triton.sh
+          export LLVM_SYSPATH=${HOME}/triton-nightly/llvm/build/
+          pip uninstall -y triton
+          cd triton/python
           python setup.py clean
           TRITON_CODEGEN_INTEL_XPU_BACKEND=1 python setup.py develop
+          python -c "import triton"
           if [ ${PIPESTATUS[0]} -ne 0 ]; then
-              echo -e "[ERROR] Private-torch BUILD FAIL"
+              echo -e "[ERROR] Triton BUILD FAIL"
               exit 1
           fi
 
@@ -103,7 +111,7 @@ jobs:
           echo "num_skipped: $num_skipped" | tee -a ./ut_summary.log
           echo "num_failed: $num_failed" | tee -a ./ut_summary.log
           echo "num_passed: $num_passed" | tee -a ./ut_summary.log
-      
+
       - name: New Failed Cases
         run: |
           echo "TODO: will add new failure cases"
@@ -129,7 +137,7 @@ jobs:
           echo "num_expected_skip_and_sucess: $num_expected_skip_and_sucess" | tee -a ./ut_summary.log
           echo "num_total_wo_mat_dot: $num_total_wo_mat_dot" | tee -a ./ut_summary.log
           echo "total_pass_rate: $total_pass_rate" | tee -a ./ut_summary.log
-      
+
       - name: Float32 Cases Pass Rate Calculate (no matmul/dot)
         run: |
           cd ${HOME}/actions-runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/triton-tests/python/test/unit
@@ -155,7 +163,7 @@ jobs:
           cd ${HOME}/actions-runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/triton-tests/python/test/unit
           cp ${HOME}/actions-runner/_work/intel-xpu-backend-for-triton/intel-xpu-backend-for-triton/triton/*.log .
           cat ut_summary.log
-      
+
       - name: Upload Triton PVC nightly Data
         uses: actions/upload-artifact@v3
         with:
