Move pre-ci before building dependencies

diff --git a/.github/workflows/triton_xpu_backend_ci.yml b/.github/workflows/triton_xpu_backend_ci.yml
--- a/.github/workflows/triton_xpu_backend_ci.yml
+++ b/.github/workflows/triton_xpu_backend_ci.yml
@@ -21,22 +21,6 @@ jobs:
           conda install -y astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses mkl mkl-include
           python3 -m pip install --upgrade pre-commit
 
-      - name: Install Dependency
-        shell: bash
-        run: |
-          set -ex
-          python --version
-          source ${HOME}/miniconda3/bin/activate triton-preci
-          python --version
-          pip install setuptools cython numpy wheel scikit-build scipy
-          ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ${HOME}/miniconda3/envs/triton-preci/lib/libstdc++.so.6
-          pip install psutil cpuid
-          bash ${HOME}/triton-preci/env_prepare_ci.sh
-          python -c "import torch;import intel_extension_for_pytorch"
-          if [ ${PIPESTATUS[0]} -ne 0 ]; then
-              echo -e "[ERROR] Private-torch or IPEX BUILD FAIL"
-              exit 1
-          fi
 
       - name: Check Pre-commit
         shell: bash
@@ -58,14 +42,32 @@ jobs:
           git branch
           python3 -m pre_commit run --all-files
 
+      - name: Install Dependency
+        shell: bash
+        run: |
+          set -ex
+          python --version
+          source ${HOME}/miniconda3/bin/activate triton-preci
+          python --version
+          pip install setuptools cython numpy wheel scikit-build scipy
+          ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 ${HOME}/miniconda3/envs/triton-preci/lib/libstdc++.so.6
+          pip install psutil cpuid
+          bash ${HOME}/triton-preci/env_prepare_ci.sh
+          python -c "import torch;import intel_extension_for_pytorch"
+          if [ ${PIPESTATUS[0]} -ne 0 ]; then
+              echo -e "[ERROR] Private-torch or IPEX BUILD FAIL"
+              exit 1
+          fi
+
       - name: Build Triton
         shell: bash
         run:  |
           cd triton/python
           python setup.py clean
           TRITON_CODEGEN_INTEL_XPU_BACKEND=1 python setup.py develop
+          python -c "import triton"
           if [ ${PIPESTATUS[0]} -ne 0 ]; then
-              echo -e "[ERROR] Private-torch BUILD FAIL"
+              echo -e "[ERROR] Triton BUILD FAIL"
               exit 1
           fi
 
